version: '3.3'

services:
  db:
   image: mysql:5.7
   volumes:
     - ./backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: somewordpress
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress

  wordpress:
   depends_on:
     - db
   image: wordpress:latest
   volumes:
     - db_data:/var/lib/mysql
     - ./web/wp-content:/var/www/html/wp-content
     - ./web/wp-content:/var/www/html/wp-content
     - wp_data:/var/www/html
   ports:
     - "3000:80"
   restart: always
   environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress

  wpcli:
    image: tatemz/wp-cli
    volumes:
      - wp_data:/var/www/html
    links:
      - db:mysql
    entrypoint: wp
    command: "--info"
volumes:
  db_data:
  wp_data:
